language: node_js
node_js:
  - 16

services:
  - docker

before_install:
  - echo "nothing needs to be installed"

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy annulus/reverseproxy:v2
  - docker tag udagram-api-user annulus/udagram-api-user:v2
  - docker tag udagram-api-feed annulus/udagram-api-feed:v2
  - docker tag udagram-frontend annulus/udagram-frontend:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tyrueiwoqp/reverseproxy:v2
  - docker push tyrueiwoqp/udagram-api-user:v2
  - docker push tyrueiwoqp/udagram-api-feed:v2
  - docker push tyrueiwoqp/udagram-frontend:v2
